const quotes = [
  '"The unexamined life is not worth living." - Socrates',
  '"Man is the only creature who refuses to be what he is." - Albert Camus',
  '"Life must be understood backward. But it must be lived forward." - Søren Kierkegaard',
  '"He who has a why to live can bear almost any how." - Friedrich Nietzsche',
  '"Happiness depends upon ourselves." - Aristotle',
  '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." - Aristotle',
  '"I think, therefore I am." - René Descartes',
  '"To be is to be perceived." - George Berkeley',
  '"One cannot step twice in the same river." - Heraclitus',
  '"Everything flows, nothing stands still." - Heraclitus',
  '"The only constant in life is change." - Heraclitus (attributed)',
  '"Knowing yourself is the beginning of all wisdom." - Aristotle',
  '"We are all in the gutter, but some of us are looking at the stars." - Oscar Wilde',
  '"Do I contradict myself? Very well then I contradict myself." - Walt Whitman',
  '"Not all those who wander are lost." - J.R.R. Tolkien',
  '"I know of no better life purpose than to perish in attempting the great and the impossible." - Friedrich Nietzsche',
  '"There is no shame in preferring happiness." - Albert Camus',
  '"The meaning of life is just to be alive." - Alan Watts',
  '"You are the universe experiencing itself." - Alan Watts',
  '"The world is full of magical things patiently waiting for our senses to grow sharper." - W.B. Yeats',
  '"We do not see things as they are, we see them as we are." - Anaïs Nin',
  '"The eye sees only what the mind is prepared to comprehend." - Robertson Davies',
  '"There is nothing either good or bad, but thinking makes it so." - William Shakespeare',
  '"The journey of a thousand miles begins with a single step." - Lao Tzu',
  '"What we think, we become." - Buddha',
  '"We are shaped by our thoughts; we become what we think." - Buddha',
  '"The present moment is the only time over which we have dominion." - Thich Nhat Hanh',
  '"Reality is merely an illusion, albeit a very persistent one." - Albert Einstein',
  '"Imagination is more important than knowledge." - Albert Einstein',
  '"The important thing is not to stop questioning." - Albert Einstein',
  '"A person who never made a mistake never tried anything new." - Albert Einstein',
  '"What is rational is actual and what is actual is rational." - G.W.F. Hegel',
  '"Man is condemned to be free." - Jean-Paul Sartre',
  '"Existence precedes essence." - Jean-Paul Sartre',
  '"The absurd is born of the confrontation between human need and the unreasonable silence of the world." - Albert Camus',
  '"In the depth of winter, I finally learned that within me there lay an invincible summer." - Albert Camus',
  '"We are a way for the cosmos to know itself." - Carl Sagan',
  '"Somewhere, something incredible is waiting to be known." - Carl Sagan',
  '"Sometimes, carrying on, just carrying on, is the superhuman achievement." - Albert Camus',
  '"The cosmos is within us. We are made of star-stuff." - Carl Sagan',
  '"The universe is under no obligation to make sense to you." - Neil deGrasse Tyson',
  '"We are all made of stories." - Ursula K. Le Guin',
  '"What is human life but a sequence of moments, each with its own meaning?" - unknown',
  '"Two things are infinite: the universe and human stupidity; and I am not sure about the universe." - Albert Einstein',
  '"The purpose of life is a life of purpose." - Robert Byrne',
  '"All we have to decide is what to do with the time that is given us." - J.R.R. Tolkien',
  '"Even the darkest night will end and the sun will rise." - Victor Hugo',
  '"The world breaks everyone, and afterward, some are strong at the broken places." - Ernest Hemingway',
  '"It is not length of life, but depth of life." - Ralph Waldo Emerson',
  '"When there is no ground beneath us, we learn to build our own." - unknown',
  '"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." - Ralph Waldo Emerson',
];

export function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}
